### ISSUE TITLE
Create shipment fails with `unknown` postage_type

### ISSUE THREAD

**Issue by timginn** [chitchats/chitchats-api-doc#16]
The documentation says to use the "unknown" postage_type "when you wish to view rates before buying postage". In the past this has worked, and, a shipment created through the API with this type could be viewed, edited and finished up on the Chitchats website.

Now, creating a shipment with this type no longer creates a shipment that can be finished up on the Chitchats website, it instead returns a 400 error {"error":{"message":"Unknown postage_type"}} yet the documentation still mentions that the "unknown" postage type is available.

There is now clearly an inconsistency between what the documentation says can be done and what the API actually allows/does.

**Comment by gshaw** [comment]
Can you attach the parameters you are using in the request.  I believe I know what the problem is and a fix should be deployed but I'd like to make sure we didn't overlook something else.

For a workaround if you can use the `unknown` postage type to buy postage if you pass a `ship_date` value.  You can use a special value of "today" instead of an actual date.  This will create an incomplete postage and return rates.  You can finish the postage without using the web UI using the `buy` endpoint and passing a `postage_type`.

I'll post here when the fix that is in the works is deployed for your to try but if you send me the request details (either here or email them through support and mention for Gerry) I'll get them.

**Comment by gshaw** [comment]
@timginn the fix for has been deployed and the documented behaviour works as expected.  If you are still running into problems please let me know. I apologize for the hassle this must have caused.
